apiVersion: v1
kind: ConfigMap
metadata:
  name: sso-extensions
data:
  sso-extensions.cli: |
    batch
    /subsystem=keycloak-server/spi=vault:add(default-provider="kubernetes-secrets")
    /subsystem=keycloak-server/spi=vault/provider=kubernetes-secrets:add(enabled=true)
    run-batch
    
